Add CI workflow
catie-aq/zephyr_honeywell-hpma115 pull request #10
Opened 2024-11-21 16:01 UTC by clementlgl

2024-11-22 08:39 UTC, clementlgl commented
Errors must be fixed in another PR.

2024-11-22 13:14 UTC, clementlgl commented on .gitignore
I think it's a good idea to use Zephyr `.gitignore`, even if it's too complete! But it excludes paths like `twister-out*`, which is interesting.
Why place it in the samples folder and not in the root directory?

2024-11-25 08:32 UTC, bperraudin commented on .gitignore
I think you're right: we should use the default one, at the root of the repository.

2024-11-25 09:30 UTC, bperraudin requested changes

2024-11-25 09:30 UTC, bperraudin commented on .github/workflows/driver.yaml
> +name: "Honeywell HPMA115 Sensor Driver CI"
May be we should name it: "Test driver"

2024-11-25 09:30 UTC, bperraudin commented on samples/sample.yaml
> +  description: Demonstration of the HPMA115 Dust Sensor driver
OK to remove the description as is done in Zephyr.

And update `name` to: "HPMA115 dust sensor sample"

2024-11-25 12:15 UTC, clementlgl commented on .gitignore
@bperraudin I have seen that the [Zephyr example application](https://github.com/zephyrproject-rtos/example-application.git) uses this [gitignore](https://github.com/zephyrproject-rtos/example-application/blob/main/.gitignore). I think we should use this one, What do you think?

2024-11-28 14:05 UTC, bperraudin approved these changes

2024-11-28 14:05 UTC, merged